import type { GameStage } from '@/types';

// ─────────────────────────────────────────────
// World 정의
// World 1: 홈로우 (asdf jkl;)
// World 2: 윗줄 (qwer uiop)
// World 3: 아랫줄 (zxcv nm,.)
// World 4: 숫자/특수
// World 5: 한글 자음/모음
// World 6: 한글 단어/문장
// World 7: 속도 챌린지 (최종)
// ─────────────────────────────────────────────

export const GAME_STAGES: GameStage[] = [
  // ─────────────── WORLD 1: 홈로우 ───────────────
  {
    id: 'w1-s1',
    world: 1,
    stage: 1,
    title: '둥지 탈출',
    description: '알에서 깨어나 처음으로 홈 포지션을 익혀요.',
    type: 'normal',
    allowedKeys: ['f', 'j'],
    lessonIds: ['en-01'],
    requiredStars: 0,
    rewards: { exp: 50, coins: 10 },
  },
  {
    id: 'w1-s2',
    world: 1,
    stage: 2,
    title: '첫 날갯짓',
    description: '왼손 홈로우 asdf를 마스터하세요.',
    type: 'normal',
    allowedKeys: ['a', 's', 'd', 'f'],
    lessonIds: ['en-02'],
    requiredStars: 1,
    rewards: { exp: 60, coins: 12 },
  },
  {
    id: 'w1-s3',
    world: 1,
    stage: 3,
    title: '오른 날개',
    description: '오른손 홈로우 jkl;을 마스터하세요.',
    type: 'normal',
    allowedKeys: ['j', 'k', 'l', ';'],
    lessonIds: ['en-03'],
    requiredStars: 3,
    rewards: { exp: 60, coins: 12 },
  },
  {
    id: 'w1-s4',
    world: 1,
    stage: 4,
    title: '양 날개 펼치기',
    description: '양손 홈로우 전체를 조합해 연습하세요.',
    type: 'normal',
    allowedKeys: ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';'],
    lessonIds: ['en-04'],
    requiredStars: 6,
    rewards: { exp: 80, coins: 15 },
  },
  {
    id: 'w1-boss',
    world: 1,
    stage: 5,
    title: '보스: 거대 지렁이',
    description: '홈로우 단어로 보스를 물리쳐라!',
    type: 'boss',
    allowedKeys: ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';'],
    lessonIds: ['en-04'],
    requiredStars: 9,
    rewards: { exp: 200, coins: 50, unlocksStageId: 'w2-s1' },
    bossConfig: {
      name: '거대 지렁이',
      hp: 100,
      targetWpm: 20,
      targetAccuracy: 85,
      timeLimit: 120,
    },
  },

  // ─────────────── WORLD 2: 윗줄 ───────────────
  {
    id: 'w2-s1',
    world: 2,
    stage: 1,
    title: '하늘을 향해',
    description: '왼손 윗줄 qwer을 배워요.',
    type: 'normal',
    allowedKeys: ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', 'q', 'w', 'e', 'r'],
    lessonIds: ['en-05'],
    requiredStars: 12,
    rewards: { exp: 80, coins: 15 },
  },
  {
    id: 'w2-s2',
    world: 2,
    stage: 2,
    title: '높이 날다',
    description: '오른손 윗줄 uiop을 배워요.',
    type: 'normal',
    allowedKeys: ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', 'u', 'i', 'o', 'p'],
    lessonIds: ['en-06'],
    requiredStars: 15,
    rewards: { exp: 80, coins: 15 },
  },
  {
    id: 'w2-s3',
    world: 2,
    stage: 3,
    title: '구름 위 단어',
    description: '홈로우 + 윗줄을 조합한 단어를 입력해요.',
    type: 'normal',
    allowedKeys: ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', 'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p'],
    lessonIds: ['en-07'],
    requiredStars: 18,
    rewards: { exp: 100, coins: 20 },
  },
  {
    id: 'w2-boss',
    world: 2,
    stage: 4,
    title: '보스: 폭풍 구름',
    description: '윗줄 단어로 폭풍을 헤쳐나가라!',
    type: 'boss',
    allowedKeys: ['a', 's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', 'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p'],
    lessonIds: ['en-07'],
    requiredStars: 21,
    rewards: { exp: 250, coins: 60, unlocksStageId: 'w3-s1' },
    bossConfig: {
      name: '폭풍 구름',
      hp: 150,
      targetWpm: 30,
      targetAccuracy: 88,
      timeLimit: 120,
    },
  },

  // ─────────────── WORLD 3: 아랫줄 ───────────────
  {
    id: 'w3-s1',
    world: 3,
    stage: 1,
    title: '땅으로 내려오다',
    description: '왼손 아랫줄 zxcv를 배워요.',
    type: 'normal',
    allowedKeys: ['a', 's', 'd', 'f', 'z', 'x', 'c', 'v'],
    lessonIds: ['en-08'],
    requiredStars: 24,
    rewards: { exp: 90, coins: 18 },
  },
  {
    id: 'w3-s2',
    world: 3,
    stage: 2,
    title: '발톱을 세우다',
    description: '오른손 아랫줄 nm,.을 배워요.',
    type: 'normal',
    allowedKeys: ['j', 'k', 'l', ';', 'n', 'm', ',', '.'],
    lessonIds: ['en-09'],
    requiredStars: 27,
    rewards: { exp: 90, coins: 18 },
  },
  {
    id: 'w3-s3',
    world: 3,
    stage: 3,
    title: '전체 알파벳',
    description: '알파벳 전체 키를 조합해 단어를 입력해요.',
    type: 'normal',
    allowedKeys: 'abcdefghijklmnopqrstuvwxyz'.split(''),
    lessonIds: ['en-10'],
    requiredStars: 30,
    rewards: { exp: 120, coins: 25 },
  },
  {
    id: 'w3-boss',
    world: 3,
    stage: 4,
    title: '보스: 대지의 곰',
    description: '아랫줄까지 포함한 단어로 곰을 물리쳐라!',
    type: 'boss',
    allowedKeys: 'abcdefghijklmnopqrstuvwxyz'.split(''),
    lessonIds: ['en-10'],
    requiredStars: 33,
    rewards: { exp: 300, coins: 70, unlocksStageId: 'w4-s1' },
    bossConfig: {
      name: '대지의 곰',
      hp: 200,
      targetWpm: 35,
      targetAccuracy: 90,
      timeLimit: 150,
    },
  },

  // ─────────────── WORLD 4: 숫자 & 특수 ───────────────
  {
    id: 'w4-s1',
    world: 4,
    stage: 1,
    title: '숫자의 세계',
    description: '숫자 키 0~9를 마스터해요.',
    type: 'normal',
    allowedKeys: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'],
    lessonIds: ['en-11'],
    requiredStars: 36,
    rewards: { exp: 100, coins: 20 },
  },
  {
    id: 'w4-s2',
    world: 4,
    stage: 2,
    title: '특수문자 정복',
    description: '자주 쓰이는 특수문자를 익혀요.',
    type: 'normal',
    allowedKeys: ['!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '-', '_', '=', '+'],
    lessonIds: ['en-12'],
    requiredStars: 39,
    rewards: { exp: 110, coins: 22 },
  },
  {
    id: 'w4-s3',
    world: 4,
    stage: 3,
    title: '코드 타이핑',
    description: '프로그래밍 코드 스타일 문장을 입력해요.',
    type: 'normal',
    allowedKeys: [...'abcdefghijklmnopqrstuvwxyz0123456789'.split(''), '(', ')', '{', '}', '[', ']', ';', ':', '"', "'", '<', '>', '/', '\\', '|', '-', '_', '=', '+'],
    lessonIds: ['en-13'],
    requiredStars: 42,
    rewards: { exp: 130, coins: 28 },
  },
  {
    id: 'w4-boss',
    world: 4,
    stage: 4,
    title: '보스: 코드 마법사',
    description: '숫자와 특수문자를 포함한 코드로 마법사를 물리쳐라!',
    type: 'boss',
    allowedKeys: [...'abcdefghijklmnopqrstuvwxyz0123456789'.split(''), '(', ')', '{', '}', ';', ':', '"', '-', '='],
    lessonIds: ['en-13'],
    requiredStars: 45,
    rewards: { exp: 350, coins: 80, unlocksStageId: 'w5-s1' },
    bossConfig: {
      name: '코드 마법사',
      hp: 250,
      targetWpm: 40,
      targetAccuracy: 90,
      timeLimit: 150,
    },
  },

  // ─────────────── WORLD 5: 한글 자음/모음 ───────────────
  {
    id: 'w5-s1',
    world: 5,
    stage: 1,
    title: '한글 세계 입문',
    description: '기본 자음 ㄱㄴㄷ를 익혀요.',
    type: 'normal',
    allowedKeys: ['ㄱ', 'ㄴ', 'ㄷ', 'ㄹ', 'ㅁ'],
    lessonIds: ['ko-01'],
    requiredStars: 48,
    rewards: { exp: 100, coins: 20 },
  },
  {
    id: 'w5-s2',
    world: 5,
    stage: 2,
    title: '자음 완성',
    description: '모든 기본 자음을 마스터해요.',
    type: 'normal',
    allowedKeys: ['ㄱ', 'ㄴ', 'ㄷ', 'ㄹ', 'ㅁ', 'ㅂ', 'ㅅ', 'ㅇ', 'ㅈ', 'ㅊ', 'ㅋ', 'ㅌ', 'ㅍ', 'ㅎ'],
    lessonIds: ['ko-02'],
    requiredStars: 51,
    rewards: { exp: 110, coins: 22 },
  },
  {
    id: 'w5-s3',
    world: 5,
    stage: 3,
    title: '모음의 흐름',
    description: '기본 모음과 이중 모음을 익혀요.',
    type: 'normal',
    allowedKeys: ['ㅏ', 'ㅓ', 'ㅗ', 'ㅜ', 'ㅡ', 'ㅣ', 'ㅐ', 'ㅔ'],
    lessonIds: ['ko-03'],
    requiredStars: 54,
    rewards: { exp: 110, coins: 22 },
  },
  {
    id: 'w5-boss',
    world: 5,
    stage: 4,
    title: '보스: 한글 수호신',
    description: '자음과 모음으로 한글 수호신을 물리쳐라!',
    type: 'boss',
    allowedKeys: ['ㄱ', 'ㄴ', 'ㄷ', 'ㄹ', 'ㅁ', 'ㅂ', 'ㅅ', 'ㅇ', 'ㅈ', 'ㅊ', 'ㅋ', 'ㅌ', 'ㅍ', 'ㅎ', 'ㅏ', 'ㅓ', 'ㅗ', 'ㅜ', 'ㅡ', 'ㅣ'],
    lessonIds: ['ko-03'],
    requiredStars: 57,
    rewards: { exp: 400, coins: 90, unlocksStageId: 'w6-s1' },
    bossConfig: {
      name: '한글 수호신',
      hp: 300,
      targetWpm: 25,
      targetAccuracy: 88,
      timeLimit: 150,
    },
  },

  // ─────────────── WORLD 6: 한글 단어/문장 ───────────────
  {
    id: 'w6-s1',
    world: 6,
    stage: 1,
    title: '첫 한글 단어',
    description: '받침 없는 기본 단어를 타이핑해요.',
    type: 'normal',
    allowedKeys: [],  // 한글 전체
    lessonIds: ['ko-05'],
    requiredStars: 60,
    rewards: { exp: 120, coins: 25 },
  },
  {
    id: 'w6-s2',
    world: 6,
    stage: 2,
    title: '받침과 함께',
    description: '받침이 있는 단어를 타이핑해요.',
    type: 'normal',
    allowedKeys: [],
    lessonIds: ['ko-07'],
    requiredStars: 63,
    rewards: { exp: 130, coins: 28 },
  },
  {
    id: 'w6-s3',
    world: 6,
    stage: 3,
    title: '한글 문장',
    description: '완전한 한글 문장을 타이핑해요.',
    type: 'normal',
    allowedKeys: [],
    lessonIds: ['ko-09'],
    requiredStars: 66,
    rewards: { exp: 150, coins: 30 },
  },
  {
    id: 'w6-boss',
    world: 6,
    stage: 4,
    title: '보스: 전설의 학',
    description: '한글 문장으로 전설의 학을 물리쳐라!',
    type: 'boss',
    allowedKeys: [],
    lessonIds: ['ko-10'],
    requiredStars: 69,
    rewards: { exp: 500, coins: 100, unlocksStageId: 'w7-s1' },
    bossConfig: {
      name: '전설의 학',
      hp: 400,
      targetWpm: 35,
      targetAccuracy: 90,
      timeLimit: 180,
    },
  },

  // ─────────────── WORLD 7: 속도 챌린지 ───────────────
  {
    id: 'w7-s1',
    world: 7,
    stage: 1,
    title: '속도의 눈',
    description: '빠른 영문 단어를 쉬지 않고 입력해요.',
    type: 'normal',
    allowedKeys: 'abcdefghijklmnopqrstuvwxyz'.split(''),
    lessonIds: ['en-17'],
    requiredStars: 72,
    rewards: { exp: 200, coins: 40 },
  },
  {
    id: 'w7-s2',
    world: 7,
    stage: 2,
    title: '한영 혼합',
    description: '한글과 영문이 혼합된 텍스트를 입력해요.',
    type: 'normal',
    allowedKeys: [],
    lessonIds: ['en-19', 'ko-19'],
    requiredStars: 76,
    rewards: { exp: 220, coins: 45 },
  },
  {
    id: 'w7-s3',
    world: 7,
    stage: 3,
    title: '극한의 속도',
    description: '타임어택 모드로 최고 속도에 도전해요.',
    type: 'normal',
    allowedKeys: [],
    lessonIds: ['en-20', 'ko-20'],
    requiredStars: 80,
    rewards: { exp: 250, coins: 50 },
  },
  {
    id: 'w7-boss',
    world: 7,
    stage: 4,
    title: '최종 보스: 하늘의 왕',
    description: '모든 실력을 발휘해 하늘의 왕이 되어라!',
    type: 'boss',
    allowedKeys: [],
    lessonIds: ['en-20', 'ko-20'],
    requiredStars: 84,
    rewards: { exp: 1000, coins: 200 },
    bossConfig: {
      name: '하늘의 왕',
      hp: 1000,
      targetWpm: 60,
      targetAccuracy: 95,
      timeLimit: 300,
    },
  },
];

export function getStagesByWorld(world: number): GameStage[] {
  return GAME_STAGES.filter(s => s.world === world);
}

export function getStageById(id: string): GameStage | undefined {
  return GAME_STAGES.find(s => s.id === id);
}

export function getUnlockedStages(totalStars: number): GameStage[] {
  return GAME_STAGES.filter(s => s.requiredStars <= totalStars);
}
